name: CI Automation for Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-automation:
    name: Run Tests and Report Results
    runs-on: ubuntu-latest  # Using Ubuntu as the OS for testing

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Setup Python (or other environment if needed)
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Step 3: Install necessary dependencies for testing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave   # Assuming 'behave' for BDD testing

      # Step 4: Run the tests
      - name: Run Behave tests
        run: |
          behave > behave_test_output.txt  # Run tests and store output in a file

      # Step 5: Publish results to GitHub Actions as a test result
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          test-results: behave_test_output.txt  # Provide the test result file

      # Step 6: Upload test results as an artifact
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: behave-test-results
          path: behave_test_output.txt

      # Step 7: Create an issue on failure
      - name: Create issue if tests fail
        if: failure()  # This step will run only if previous steps failed
        uses: dacbd/create-issue-action@v4
        with:
          title: "Test Suite Failure - $(date +'%Y-%m-%d %H:%M:%S')"  # Issue title with date
          body: |
            The tests have failed. Below is the output of the test run:
            ```
            $(cat behave_test_output.txt)
            ```  # Display test result details in the issue
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for issue creation

