name: Automated CI Pipeline for Behave

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    name: Automated CI Pipeline
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Step 3: Install testing tools
      - name: Install Behave and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave

      # Step 4: Extract source code and test scripts
      # This is handled by the repository checkout step above

      # Step 5: Run Behave tests
      - name: Run Behave tests
        run: |
          behave > behave_test_output.txt

      # Step 6: Upload test results as artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: behave-test-results
          path: behave_test_output.txt

      # Step 7: Create an issue on failure
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Test Suite Failure - $(date +'%Y-%m-%d %H:%M:%S')"
          content-filepath: behave_test_output.txt
