name: Automated CI Pipeline for Behave

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    name: behave-testing
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List repo
        run: |
          ls

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Step 3: Install testing tools
      - name: Install Behave and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave

      # Step 4: Extract source code and test scripts
      # This is handled by the repository checkout step above

      # Step 5: Run Behave tests
      - name: Run Behave tests
        run: |
          behave

      - name: Run behave tests 2
        uses: cryptic-wizard/run-behave-tests@v0.4.0
        with:
          test-output-name: results.txt



      # Step 5: Run Behave tests
      - name: Run Behave tests
        run: |
          behave > behave_test_output.txt

      # Step 6: Upload test results as artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: behave-test-results
          path: behave_test_output.txt

      # Step 7: Create an issue on failure
      # - name: Create issue on failure
      #   if: failure()
      #   uses: nashmaniac/create-issue-action@v1.1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     title: "Test Suite Failure - $(date +'%Y-%m-%d %H:%M:%S')"
      #     content-filepath: failure_output.txt


      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Simple test issue
          body: my new issue

